# Set the names of your parameters in this file

# Your image registry url,
# For example, if you are using `ghcr.io`, this will be `ghcr.io/<your-github-username>`
# registry_prefix = "<your-registry-prefix>"
registry_prefix = "ghcr.io/ppiegaze"

# This image is used by the ContainerTask obtaining the dataset with the Kaggle API
# This should be a full name plus tag. For example, "kaggle-task-image:latest".
# kaggle_task_image_name = "<your-kaggle-task-image-name-and-tag>"
kaggle_task_image_name_and_tag = "kaggle-task-image:latest"

# This image is used by the task deduplicating the dataset, and is utilized in the ImageSpec
# This should be just the image name without a tag (the ImageSpec builder will provide the tag)
# For example, "dedupe-task-image".
# dedupe_task_image_name = "<your-dedupe-task-image>"
dedupe_task_image_name = "dedupe-task-image"

# You should have a secret ARN that looks like this:
# `arn:aws:secretsmanager:<your-region>:<your-account-id>:secret:<your-secret-name>-<autogenerated-suffix>`
# You need to divide it up into two strings:
# The part of the ARN up to and including `:secret:`
# SECRET_GROUP = "arn:aws:secretsmanager:<your-region>:<your-account-id>:secret:"
SECRET_GROUP = "arn:aws:secretsmanager:us-east-2:356633062068:secret:"

# And the part of the ARN after `:secret:`
# SECRET_KEY = "<your-secret-name>-<autogenerated-suffix>"
SECRET_KEY = "peeter-kaggle-nwGofC"

# The name of the project where you registered the workflow
# target_project = "<your-target-project-name>"
target_project = "wine"

# The name of the domain where you registered the workflow
# target_domain = "<your-target-domain-name>"
target_domain = "development"
